services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile_back
    container_name: backend
    environment:
      - IS_DOCKER=True
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
      - ./data:/app/data
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile_front
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    depends_on:
      - backend
