# Utilisation de Node.js 18
FROM node:18

# Répertoire de travail
WORKDIR /app/front

# Copier les fichiers nécessaires
COPY front/package.json front/package-lock.json ./

# Installer les dépendances avec legacy-peer-deps
RUN npm install

# Activer OpenSSL legacy
ENV NODE_OPTIONS=--openssl-legacy-provider

# Copier les fichiers restants
COPY front/ ./

# Construire l'application
RUN npm run build

# Exposer le port
EXPOSE 3000

# Démarrer l'application
CMD ["npm", "start"]
